name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.2.0
  intl: ^0.20.2
  floor: any
  retrofit: ^4.7.1
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.2.0
  ionicons: ^0.2.2

  # Firebase y Google Sign-In (versiones actualizadas)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^6.0.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.2.0
  floor_generator: ^1.5.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
